language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - php: 5.6
  - php: 5.6
    env: deps=low
  - php: 7.0
  - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache/files


before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar validate
  - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; else php composer.phar install --dev fi

script: ./vendor/bin/phpunit -vvv

