language: php
matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: deps=low
    - php: 7.0
    - php: 7.1

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
    - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; fi

script:
  - composer validate
  - composer update
  - bin/phpunit -vvv

install:
    - travis_retry composer install

