language: php

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: deps=low
    - php: 7.0
    - php: 7.1

before_script:
  - composer validate
  - if [[ $deps = low ]]; then composer update --prefer-lowest --prefer-stable; else composer update --dev; fi

script: ./bin/phpunit -vvv

